spring:
  application:
    name: redisClientApps
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQLDialect
        format-sql : true
    show-sql: true  cache:    type: redis    redis:      cache-null-values: false
      time-to-live: 0  redis:    host: localhost
    database: 0    port: 6379
      
    
server:  servlet:    context-path: /redisClientApps
